### ISSUE TITLE
CI is failing because of the exception in test_api_example

### ISSUE THREAD

**Issue by Annapooraniqxf2** [qxf2/qxf2-page-object-model#231] opened 2020-05-21 08:54 UTC
Noticed a failure in CI but after sometimes it passes.
The reason for the failure is
**failure | FAIL:** Total car count doesnt match expected count 
2020-05-20 17:01:37.427 | INFO     | utils.Base_Logging:write:102 - write | Exception when trying to run test:/root/project/tests/test_api_example.py 
2020-05-20 17:01:37.429 | INFO     | utils.Base_Logging:write:102 - write | Python says:
**FAILED**

Source: https://app.circleci.com/pipelines/github/qxf2/qxf2-page-object-model/87/workflows/02867021-1c27-435f-a0bb-627101205b18

**Comment by qxf2** [comment] 2020-05-21 11:38
@rajiqxf2 - this does not seem to happen very often. In fact, yesterday was the first time I noticed this error. Can you please investigate and think of what might be causing such flakiness? Leave it open if you cannot find the root cause.

To be clear, the same test passed with multiple version of Python and failed for just Python3.6 one time. Upon a rerun, the same test passed.

**Comment by akkuldn** [comment] 2020-06-08 10:47
This issue is happening because the three CircleCI containers are trying to access the cars API at the same time
A scenario of failure:
1) The first CircleCI container tries to access the cars API, It will first get the initial count of cars, say 162.
2) To this, it would add a new car and verify if the count is correctly 163.
3) At this point, the second container would try to get the initial car count, but it would get the initial count itself as 163 as it was added directly to the server by the first container.
4) To this, the second container adds a car and the count be 164.
5) The first container then tries to delete the car it had added and verify if the count is 162, as 162 was the initial count it had registered, but the count would fail to match as the car would be deleted from 164 cars making the total 163 causing the test to fail.

**Comment by akkuldn** [comment] 2020-06-08 10:48
The issue can be resolved by using localhost instance on each container rather than the cars API webserver.
- Clone the cars API repo from Github in circle.yml
- Run the cars_app flask application as a background process in circle.yml file
- Change the api_url in test_api_example from http://35.167.62.251/ to 127.0.0.1:5000

**Closed** 2020-06-18 09:36 UTC
