### ISSUE TITLE
Delete some of the pointless string statements identified by Codacy

### ISSUE THREAD

**Issue by qxf2** [qxf2/qxf2-page-object-model#222] opened 2020-05-15 08:24 UTC
Codacy notices 3 pointless string statements in our code base. Please remove them.

https://app.codacy.com/manual/qxf2/qxf2-page-object-model/issues?bid=16560353&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6W119LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6WyJXYXJuaW5nIl19LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjE3OCJdfSx7ImlkIjoiQXV0aG9yIiwidmFsdWVzIjpbXX1d

**Comment by rahul-qxf2** [comment] 2020-06-01 09:28
@qxf2 ,

Removed the following two statements from the endpoints/API_Player.py file.

"""if userlist result is none then return http error code"""
"verify result based on user list and response code"
I did not remove the following statement from utils/email_pytest_report.py as this statement was closing part of the comment.

'''

[codacy check](https://app.codacy.com/manual/qxf2/qxf2-page-object-model/commit?cid=471019083&fileBranchId=18398770) is also passed for this commit.

Let me know in case you have any comments otherwise, I will share the same with code reviewer.

**Comment by rahul-qxf2** [comment] 2020-06-01 13:35
@qxf2 , sorry you can ignore this as I think you have already confirmed this can go to code reviewer in below PR request:
`https://github.com/qxf2/qxf2-page-object-model/pull/235`
I will delete additional PR `https://github.com/qxf2/qxf2-page-object-model/pull/236` once PR-235 is merged.

**Comment by Annapooraniqxf2** [comment] 2020-06-01 16:11
Since we are removing the commented lines from API_player.py and the codacy is also passed. I am closing this issue

**Closed by Annapooraniqxf2** 2020-06-01 16:11 UTC
Labels: bug, good first issue, help wanted
